### PR TITLE
Update raster-grid.scss

### PR DESCRIPTION
**Pull request by kulturpessimist**
bugfix for media queries min- and max width interchanged

### CODE REVIEW

**Comment by johannschopplich** [comment]
Thanks, good catch!

**Comment by kulturpessimist** [comment]
Thanks for merging so fast. Will you publish an Update to npm too?

**Comment by johannschopplich** [comment]
Of course, just did. Thanks for mentioning it, otherwise I would have forgotten.

**Comment by kulturpessimist** [comment]
Great so i can switch my dependencie back to your project. Thanks dude.

**Pull request merged**
